import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Portfólio | Arlisson Costa - Desenvolvedor Full-stack</title>
      <meta
        name="google-site-verification"
        content="vVnMGXO52-j1-rjcLtO83tlmk8_SU_30hogplCwRAms"
      />
      <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
      <meta
        name="description"
        content="Desenvolvedor Full-stack com foco em Next.js e .NET"
      />
      <meta
        name="keywords"
        content="sites, sistemas web, desenvolvimento, frontend, backend, arlisson costa, fullstack, arlisson, desenvolvedor .net, dotnet, freela, nextjs, portfolio"
      />
      <meta name="author" content="Arlisson Costa" />
      <body>{children}</body>
    </html>
  );
}
